# version: '3.9'

services:
  # Commented because it is now running on raspberry pi
  # postgres:
  #   image: pgvector/pgvector:pg16
  #   container_name: legal-ai-db
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #     - ./backend/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: legal-ai-api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./data:/data
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    
  # Commented because it is now running on raspberry pi
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: legal-ai-pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "admin@legal.com"
  #     PGADMIN_DEFAULT_PASSWORD: "admin"
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data:
  #huggingface_cache: 